language: node_js
node_js:
  - lts/carbon # version 8
  - lts/dubnium # version 10
  - node # latest
os:
  - windows
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
