language: node_js
node_js:
  - lts/carbon # version 8
  - lts/dubnium # version 10
  - 12 # version 12
os:
  - windows
  - linux
  - osx
matrix:
  allow_failures:
    - os: windows
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
