environment:
  matrix:
    - nodejs_version: "8" # maintainance lts
    - nodejs_version: "10" # curent lts
    - nodejs_version: "11" # latest

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
